server:
  port: 5001

spring:
  redis:
    host: 114.117.162.48
    port: 6379
    database: 3
    password: xiehuan
  datasource:
    # type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cdb-4tu4mj0t.sql.tencentcdb.com:63257/eng?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: daxing
    password: daxing!3
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      max-lifetime: 0
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

wx:
  mp:
    configs:
      - appId: wxd21e6ebff222d813 # 第一个公众号的appid
        secret: 650eb045a499f0a58ce83f802ec04dc7 # 公众号的appsecret
        token: 111 # 接口配置里的Token值
        aesKey: 111 # 接口配置里的EncodingAESKey值
  miniapp:
    configs:
        #微信小程序的appid
      - appid: wx123123
        #微信小程序的Secret
        secret: wx123123
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
        spbillCreateIp: 111.230.70.100
  pay:
    appId: wx88c75ddb7c18587e #微信公众号或者小程序等的appid
    mchId: 1586237971 #微信支付商户号
    mchKey: Wxf80magic2020kingbearfly2021041 #微信支付商户密钥
    #    subAppId: #服务商模式下的子商户公众账号ID
    #    subMchId: #服务商模式下的子商户号
    keyPath: classpath:apiclient_cert.p12 # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
pay:
  wxNotifyUrl: http://139.155.46.177:5001/notify/wx/notify/order
  wxRefundNotifyUrl: http://139.155.46.177:5001/notify/wx/refundNotify/order

qcloud:
  secret-id: AKIDIQIyRdYCZfT0GFxOXT8XfW6PQAeqlPmt
  secret-key: rRkmY3HFwMVNyIL7cqnTt2vXtxkGUR7W
  region-name: ap-chongqing
  bucket-name: lhkj-1252013013
  domain-name: https://lhkj-1252013013.cos.ap-chongqing.myqcloud.com/